services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: mercatura
      POSTGRES_PASSWORD: mercatura
      POSTGRES_DB: mercatura
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  cache:
    image: redis
    ports:
      - "6379:6379"