CREATE TABLE IF NOT EXISTS users (
    id SEQUENCE PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS product(
    id SEQUENCE PRYMARY KEY,
    name TEXT NOT NULL UNIQUE,
    price INTEGER NOT NULL,
    quantity BIGINT NOT NULL,
    category TEXT NOT NULL,
);
